### ISSUE TITLE
Rserve::Connection::EvalError: eval failed

### ISSUE THREAD

**Issue by BeGe78** [clbustos/Rserve-Ruby-client#28]
Hello,
Recently i discovered that my application had an error when doing an evaluation and i succeed to reproduce it easily with:
irb
irb(main):001:0> require 'rserve'
=> true
irb(main):002:0> con=Rserve::Connection.new
=> #<Rserve::Connection:0x0000560de8c59b20 @auth_req=false, @transfer_charset="UTF-8", @auth_type=0, @hostname="127.0.0.1", @port_number=6311, @max_tries=5, @cmd_init="R CMD Rserve", @proc_rserve_ok=#<Proc:0x0000560de8c599e0@/usr/local/share/gems/gems/rserve-client-0.3.5/lib/rserve/connection.rb:61 (lambda)>, @username=nil, @password=nil, @session=nil, @tries=0, @connected=true, @s=#<TCPSocket:fd 9>, @rt=#<Rserve::Talk:0x0000560de8c59968 @io=#<TCPSocket:fd 9>>, @rsrv_version=103, @protocol="QAP1", @last_error="OK">
irb(main):003:0> x=con.eval('x<-rnorm(1)')
Rserve::Connection::EvalError: eval failed: 
        from /usr/local/share/gems/gems/rserve-client-0.3.5/lib/rserve/connection.rb:212:in `eval'
        from (irb):3
        from /usr/bin/irb:11:in `<main>'

I am using rserve-client 0.3.5, ruby 2.4.4 and R 3.5.0 on fedora 27.
I don't know precisely when this problem appeared but only recently (less than 2 weeks) as i test my application frequently.
Have an idea of what happens?

**Comment by BeGe78** [comment]
Hello, 
is there someone looking at this issue?

**Comment by BeGe78** [comment]
The problem was coming from a new version of R which need a reinstallation of Rserve. Problem is fixed.

**Comment by BeGe78** [comment]
Issue is closed

**Comment by clbustos** [comment]
Sorry for the delayed reply. I'm glad the problem is solved.
